// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vita.Goals.Infrastructure.Sql;

namespace Vita.Persistance.Sql.Migrations
{
    [DbContext(typeof(GoalsDbContext))]
    [Migration("20200515232545_Initial Database")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vita.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afaf1663-9fac-40aa-a954-18b7c6b60e6d"),
                            Color = "skyblue",
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = new Guid("57813808-4fb0-4a43-9dd7-2088879f4451"),
                            Color = "crimson",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("47c4002b-7e2b-4ea2-9b14-c0e7079b994f"),
                            Color = "darkorange",
                            Name = "VideoGames"
                        },
                        new
                        {
                            Id = new Guid("cef48041-89ee-46ce-9288-ea179e51ea41"),
                            Color = "lightslategray",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("6d89f7fa-1713-43fb-86db-23f3d58c8471"),
                            Color = "deeppink",
                            Name = "Study"
                        },
                        new
                        {
                            Id = new Guid("0af68196-cf25-44f0-88f1-fda784074575"),
                            Color = "springgreen",
                            Name = "TV Series"
                        },
                        new
                        {
                            Id = new Guid("0d3558b0-24ae-4b2b-9e96-f8eaf8a43a56"),
                            Color = "turquoise",
                            Name = "Movies"
                        },
                        new
                        {
                            Id = new Guid("8af37209-2f7c-4cf1-bc96-075b835e1715"),
                            Color = "darkslateblue",
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("6b9db6ae-ed80-4ccc-ba76-ffeaa110bc8c"),
                            Color = "limegreen",
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("92d41e17-05a2-4721-88f3-d303d8dc9785"),
                            Color = "lightseagreen",
                            Name = "Places"
                        },
                        new
                        {
                            Id = new Guid("f0dc8c7c-e943-456d-ac49-9c99c0ac9ab6"),
                            Color = "darkcyan",
                            Name = "Podcasts"
                        },
                        new
                        {
                            Id = new Guid("39609025-e42a-483b-a8dc-b25de68dab28"),
                            Color = "dodgerblue",
                            Name = "Bar & Clubs"
                        },
                        new
                        {
                            Id = new Guid("117aac89-8589-4a64-99bd-616bd86b9e3d"),
                            Color = "tomato",
                            Name = "Restaurants"
                        });
                });

            modelBuilder.Entity("Vita.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Vita.Domain.Models.Category", b =>
                {
                    b.HasOne("Vita.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
